### ISSUE TITLE
tictactoe checklist

### ISSUE THREAD

**Issue by TheRealChrisM** [TheRealChrisM/APCompSciA#1]
- [x] Play game with opponent
- [x] prevent loosing turn
- [x] when its over
- [x] who won
